config/routes.rb
CensoredTweets::Application.routes.draw do
  
  root :to => "tweets#index"
  
  devise_for :users, :skip => [:sessions] do
    get 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  resources :users
  
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#fail'

  
  match '/newest' => 'tweets#newest', :as => :newest
  match '/best' => 'tweets#best', :as => :best
  match '/head2head' => 'tweets#head2head', :as => :head2head
  match '/poll_twitter' => 'tweets#poll_twitter'
  match '/upvote/:id' => 'tweets#upvote', :as => :upvote_tweet
  match '/about' => 'tweets#about', :as => :about  
  resources :winners
  
  
    
    

end

app/models/tweet.rb
class Tweet
  include MongoMapper::Document
  
  one :twitter_status
  
  key :tweeter
  key :tweeters_follower_count,           Integer, :default => 0
  key :censored_tweeter
  key :censored_tweeters_follower_count,  Integer, :default => 0

  key :points,                            Integer, :default => 0
  key :points_all_time,                   Integer, :default => 0
  
  key :vote_count,                        Integer, :default => 0
  key :voter_user_ids,                    Array, :typecast => 'ObjectId'
  
  timestamps!
  
  before_save(:on => :create) { self.initialize_points if self.new? }
  
  scope :todays_best, sort(:points => -1)
  scope :newest, sort("twitter_status.status_created_at" => -1)
  scope :with_twitter_uid, lambda { |uid| where( "tweeter.id_str" => uid ) }
  
  def self.two_random_tweets(user)
    tweets = Tweet.where(:created_at => {"$gt" => Time.zone.now - 36.hours})
    tweets = tweets.where( "voter_user_ids" => { "$ne" => user.id} ) if user
    tweets = tweets.limit(50).all
      
    id1 = rand(tweets.size)
    id2 = rand(tweets.size) until id2 != id1 and id2 != nil unless tweets.size < 2
    return tweets[id1], (id2 ? tweets[id2] : nil)
  end
  
  def initialize_points
    self.points = self.points_all_time = self.tweeters_follower_count + self.censored_tweeters_follower_count
    
    User.add_points_to_user_by_uid(self.tweeter["id_str"], self.points)
  end
  
  def upvote!(voter)
    return false if self.voter_user_ids.include? voter.id
    
    self.vote_count += 1
    self.voter_user_ids << voter.id
    
    points_to_add = [(voter.points / 3.33).round, 7].max
    
    self.points += points_to_add
    self.points_all_time += points_to_add
    
    self.save
    
    User.add_points_to_user_by_uid(self.tweeter["id_str"], points_to_add)
  end
  
  
end

app/controllers/tweets_controller.rb
require 'twitter_poller'

class TweetsController < ApplicationController
  before_filter :authenticate_user!, :only => [:upvote]

  def index
    @tweets = Tweet.newest.limit(33).all
    @winner = Winner.most_recent.first

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tweets }
    end
  end

  def newest
    @tweets = Tweet.newest.limit(33).all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tweets }
    end
  end
  
  def best
    @tweets = Tweet.todays_best.limit(33).all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @tweets }
    end
  end
    
  def upvote
    @tweet = Tweet.find_by_id(params[:id])
    
    @did_vote = (@tweet ? @tweet.upvote!(current_user) : false)
    
    respond_to do |format|
      format.js
      format.html { redirect_to head2head_path }
      format.xml  { render :xml => @tweets }
    end
  end

  # GET /tweets/1
  # GET /tweets/1.xml
  def show
    @tweet = Tweet.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @tweet }
    end
  end
  
  def head2head
    @tweets = Tweet.two_random_tweets(current_user)
    
    respond_to do |format|
      format.html # head2head.html.erb
      format.xml  { render :xml => @tweet }
    end
  end
  
  def about
    
  end
  
  def poll_twitter
    @new_results = Twitter::Poller.search("#censoredtweet")
  end

end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/tweets/_tweet.html.erb
<div class="tweet" id="tweet-<%= tweet.id %>">

  <div class="tweet-body">
    <div class="tweet-text">
      <div class="inner">
        <%= tweet.twitter_status.text %>
      </div>
    </div>
    <div class="tweet-actions">
      <%= render :partial => "tweets/upvote", :locals => { :tweet => tweet } %>
      <div class="twitter-intents">
        <%= image_tag('http://si0.twimg.com/images/dev/cms/intents/icons/retweet.png', :class => "intent-retweet-"+tweet.id) %>
      	<%= image_tag('http://si0.twimg.com/images/dev/cms/intents/icons/reply.png', :class => "intent-reply-"+tweet.id) %>
      	<%= image_tag('http://si0.twimg.com/images/dev/cms/intents/icons/favorite.png', :class => "intent-favorite-"+tweet.id) %>
      </div>
    </div>
  </div>
  
  <div class="tweeter">
    <%= image_tag('tail.png', :class => "tail") %>

    <div class="user">
      <div class="user-image">
        <%= image_tag tweet.tweeter["profile_image_url"] %>
      </div>
      <div class="user-info">
        <%= tweet.tweeter["name"] %> | 
        @<%= tweet.tweeter["screen_name"] %>
        <br />
        <span class="time">
          <%= time_ago_in_words(tweet.twitter_status.status_created_at) %> ago
        </span>
      </div>
    </div>
    
    <div class="scores">
      <div class="inner">
        <%= tweet.points %> points<br />
        <%= tweet.vote_count %> votes
      </div>
    </div>
  
  </div>
  

	
</div>

<% content_for :javascript do -%>
	$(".intent-retweet-<%= tweet.id %>").click(function(){
		window.open("http://twitter.com/intent/retweet?tweet_id=<%= tweet.twitter_status.tweet_id.to_s %>",'','width=600,height=380,top=117,left=300,chrome=1,centerscreen=1,menubar=0,toolbar=0,location=0,statusbar=0,scrollbars=1');return false;});
	$(".intent-reply-<%= tweet.id %>").click(function(){
		window.open("http://twitter.com/intent/tweet?in_reply_to=<%= tweet.twitter_status.tweet_id.to_s %>",'','width=600,height=380,top=117,left=300,chrome=1,centerscreen=1,menubar=0,toolbar=0,location=0,statusbar=0,scrollbars=1');return false;});
	$(".intent-favorite-<%= tweet.id %>").click(function(){
		window.open("http://twitter.com/intent/favorite?tweet_id=<%= tweet.twitter_status.tweet_id.to_s %>",'','width=600,height=380,top=117,left=300,chrome=1,centerscreen=1,menubar=0,toolbar=0,location=0,statusbar=0,scrollbars=1');return false;});
<% end -%>

app/views/tweets/_upvote.html.erb
<div id="upvote-holder-for-<%= tweet.id %>" class="upvote-holder <%= (current_user and current_user.has_voted_for(tweet)) ? 'voted' : '' %>" >
  <% if current_user %>  
    <% if current_user.has_voted_for(tweet) %>
      you voted
    <% else %>
      <%= link_to "upvote ▲", upvote_tweet_path(tweet), :remote => local_assigns[:not_remote] ? false : true %>
    <% end -%>
  <% else %>  
    <%= link_to "upvote ▲", "/auth/twitter?origin=#{upvote_tweet_path(tweet)}" %>  
  <% end %>
</div>

app/views/tweets/about.html.erb
<div id="content">
	<h1>Who's who in this ***** project:</h1>
	<h3>(appearing in ****** order)</h3>
	<h2>Dan Spinosa</h2>
	<p>For a guy with such long ****, it might be easy to mistake Dan for Jesus. In reality, he's more of a Guy***** ******wood.  In his own words, Dan loves "******* on **** and ******** with his hands." Dan talks incessantly about ******* Steve Jobs.  We're pretty sure if they ever ****, they'll both be wearing black *********** and holding each others *******.  Somebody take a picture of that.</p>
	<h2>Joe Yevoli</h2>
	<p>Joe played a lot of ******** in college. As as result, he knows a lot about hanging out in ****** rooms and watching people ******.  As an Italian, Joe has an affinity for eating ******* and ******** horse **** on beds. </p>
	<h2>Henry Sztul</h2>
	<p>Though he didn't go to school to learn how to ****, Henry's a pretty resourceful scientist with a giant ******, so with a little practice ******, he was able to hone his skills on his own.  Henry loves **** so much, he's the only one on the team who has earned the title  "**** scientist."</p>
	<h2>Rebecca Zhou</h2>
	<p>Rebecca is probably the only girl we know who would **** with a team of guys like this.  As you can see from the picture above, she's really into **** cats.  When she's not ********* things on the internet... well. Nevermind.  She's always ********* things on the internet.</p>
	<h2>Chris Kurdziel</h2>
	<p>What a ****ing weirdo...</p>
</div>

<% content_for :nav do -%>
	<div id="nav">
		<ul class="nav">
			<%= link_to root_path do %>
				<li>home</li>
			<% end %>
			<%= link_to best_path do %>
				<li>best</li>
			<% end %>
			<%= link_to newest_path do %>
				<li>new</li>
			<% end %>
			<%= link_to head2head_path do %>
				<li>head 2 ****</li>
			<% end %>
			<%= link_to '/about' do %>
				<li class="about current">about</li>
			<% end %>
		</ul>
	</div>
<% end -%>

app/views/tweets/best.html.erb
<div id="content">
  <div class="tweets">
    <h2><span>today's best #censoredtweet's</span></h2>
    <%= render @tweets %>
  </div>
</div>

<div id="sidebar">

</div>

<% content_for :nav do -%>
	<div id="nav">
		<ul class="nav">
			<%= link_to root_path do %>
				<li>home</li>
			<% end %>
			<%= link_to best_path do %>
				<li class="current">best</li>
			<% end %>
			<%= link_to newest_path do %>
				<li>new</li>
			<% end %>
			<%= link_to head2head_path do %>
				<li>head 2 ****</li>
			<% end %>
			<%= link_to '/about' do %>
				<li class="about">about</li>
			<% end %>
		</ul>
	</div>
<% end -%>

app/views/tweets/head2head.html.erb
<div class="head2head">
	<div id="content">

	  <h2><span> Two Tweets, **** to Head </span></h2>


	  <div id="tweet_1" class="tweets">
	    <% if @tweets[0] %>
		  	<div class="tweet">
		  		<span class="tweet-text">
		  			<%= @tweets[0].twitter_status.text %>	
		  		</span>
		  	</div>

	    	<div class="bottom-bar">
		  		<%= image_tag @tweets[0].tweeter["profile_image_url"], :class=> "avatar"%>
	    		<%= @tweets[0].tweeter["name"] %> | @<%= @tweets[0].tweeter["screen_name"] %>
					<div class="vote">
		    		<%= render :partial => "tweets/upvote", :locals => { :tweet => @tweets[0], :not_remote => true } %>
		    	</div>
	    	</div>    	
	    <% else %>
	      You've voted on everything, sorry
	    <% end %>
	  </div>

	  <div id="versus"></div>

	  <div id="tweet_2" class="tweets">
	    <% if @tweets[1] %>
		  	<div class="tweet">
		  		<span class="tweet-text">
		  			<%= @tweets[1].twitter_status.text %>			
		  		</span>
		  	</div>

	    	<div class="bottom-bar">
		  		<%= image_tag @tweets[1].tweeter["profile_image_url"], :class=> "avatar"%>
	    		<%= @tweets[0].tweeter["name"] %> | @<%= @tweets[1].tweeter["screen_name"] %>
		    	<div class="vote">
		    		<%= render :partial => "tweets/upvote", :locals => { :tweet => @tweets[1], :not_remote => true } %>
		    	</div>
	    	</div>

	    <% else %>
	      You've voted on everything else.  You vote alot.  Wtf.
	    <% end %>
	  </div>

	</div>
	
</div>

<% content_for :nav do -%>
	<div id="nav">
		<ul class="nav">
			<%= link_to root_path do %>
				<li>home</li>
			<% end %>
			<%= link_to best_path do %>
				<li>best</li>
			<% end %>
			<%= link_to newest_path do %>
				<li>newest</li>
			<% end %>
			<%= link_to head2head_path do %>
				<li class="current">head 2 ****</li>
			<% end %>
			<%= link_to '/about' do %>
				<li class="about">about</li>
			<% end %>
		</ul>
	</div>
<% end -%>

app/views/tweets/index.html.erb
<div id="content">
  <% if @winner %>
    <div class="winners">
      <h2><span>#censoredtweet of the day</span></h2>
      <div class="winner-section">
        <%= render :partial => "winners/show", %>
        <div class="explanation">
          <div class="inner">
            everyday at midnight we *** the tweet with the most up***** from that day,
            then we do **** to it & tweet it out.  your life goal should be to **** this great honor.
          </div>
        </div>
      </div>
    </div>

  <% end -%>

  <div class="tweets">
    <h2><span>newest #censoredtweet's</span></h2>
    <%= render @tweets %>
  </div>
</div>

<div id="sidebar">  
  <%= image_tag 'side-2.png', :class=>'sidebar-2' %>
	<%= image_tag 'pride.png', :class=>'sidebar-2', :width=>"230px" %>
</div>

<% content_for :nav do -%>
	<div id="nav">
		<ul class="nav">
			<%= link_to root_path do %>
				<li class="current">home</li>
			<% end %>
			<%= link_to best_path do %>
				<li>best</li>
			<% end %>
			<%= link_to newest_path do %>
				<li>new</li>
			<% end %>
			<%= link_to head2head_path do %>
				<li>head 2 ****</li>
			<% end %>
			<%= link_to '/about' do %>
				<li class="about">about</li>
			<% end %>
		</ul>
	</div>
<% end -%>

app/views/tweets/newest.html.erb
<div id="content">

  <div class="tweets">
    <h2><span>newest #censoredtweet's</span></h2>
    <%= render @tweets %>
  </div>

</div>

<div id="sidebar">

</div>

<% content_for :nav do -%>
	<div id="nav">
		<ul class="nav">
			<%= link_to root_path do %>
				<li>home</li>
			<% end %>
			<%= link_to best_path do %>
				<li>best</li>
			<% end %>
			<%= link_to newest_path do %>
				<li class="current">newest</li>
			<% end %>
			<%= link_to head2head_path do %>
				<li>head 2 ****</li>
			<% end %>
			<%= link_to '/about' do %>
				<li class="about">about</li>
			<% end %>
		</ul>
	</div>
<% end -%>

app/views/tweets/poll_twitter.html.erb
<div style="text-align:center;">
	<h1>Polling Twitter for new search results...</h1>
	<hr/>
	<h1>Just found <%= @new_results.count %> new tweets</h1>
</div>

<% content_for :javascript do -%>
	$(document).ready(function(){
		setTimeout(function(){location.reload(true);},10000);
	});
<% end -%>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @tweet %>

<%= link_to 'Home', root_path %>

app/views/tweets/upvote.js.erb
$("#tweet-<%= @tweet.id %>").replaceWith( '<%= escape_javascript(render :partial => "tweets/tweet", :locals => { :tweet => @tweet }) %>' );
$("#tweet-<%= @tweet.id %>").effect('highlight', {}, 10000);