config/routes.rb
CensoredTweets::Application.routes.draw do
  
  root :to => "tweets#index"
  
  devise_for :users, :skip => [:sessions] do
    get 'signout' => 'devise/sessions#destroy', :as => :destroy_user_session
  end
  resources :users
  
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => 'authentications#fail'

  
  match '/newest' => 'tweets#newest', :as => :newest
  match '/best' => 'tweets#best', :as => :best
  match '/head2head' => 'tweets#head2head', :as => :head2head
  match '/poll_twitter' => 'tweets#poll_twitter'
  match '/upvote/:id' => 'tweets#upvote', :as => :upvote_tweet
  match '/about' => 'tweets#about', :as => :about  
  resources :winners
  
  
    
    

end

app/models/winner.rb
class Winner
  include MongoMapper::Document
  
  belongs_to :tweet
  
  key :background_image,    String
  key :tweet_points_at_win, Integer
  
  timestamps!
  
  scope :most_recent, sort(:created_at => -1)
  
  def self.declare_winner!
    winning_tweet = Tweet.todays_best.first
    
    # 1) Capture Winner
    w = Winner.new
    w.tweet = winning_tweet
    w.tweet_points_at_win = winning_tweet.points
    w.background_image = "/images/winner_bgs/"+BACKGROUND_IMAGES[rand(BACKGROUND_IMAGES.size)]
    w.save
    
    # 2) Reset tweets points
    Tweet.collection.update({}, { '$set' => {'points' => 0} }, :multi => true)

    return w
  end
  
  BACKGROUND_IMAGES = Dir.entries("public/images/winner_bgs/").select { |n| n.end_with?(".png") or n.end_with?(".jpg") }
  
end

app/controllers/winners_controller.rb
class WinnersController < ApplicationController

  # GET /winners
  # GET /winners.xml
  def index
    @winners = Winner.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @winners }
    end
  end

  # GET /winners/1
  # GET /winners/1.xml
  def show
    @winner = Winner.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @winner }
    end
  end

end

app/helpers/winners_helper.rb
module WinnersHelper
end

app/views/winners/_show.html.erb
<div class="winner">
  
  <%= image_tag @winner.background_image, :class => "bg-image" %>
  <div class="tweet-text">
    <%= @winner.tweet.twitter_status.text %>
  </div>

  <div class="tweeter">
  
    <div class="avatar">
      <%= image_tag @winner.tweet.tweeter["profile_image_url"] %>
    </div>
    
    <div class="tweeter-info">
      censored twat by @<%= @winner.tweet.tweeter["screen_name"] %>
      <br />
      <%= @winner.tweet.points %> points |
      <%= @winner.tweet.vote_count %> votes |
      <%= @winner.created_at.to_s(:long_date) %>
    </div>

  </div>

  
  
  

</div>

app/views/winners/index.html.erb
<h1>Listing winners</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @winners.each do |winner| %>
  <tr>
    <td><%= link_to 'Show', winner %></td>
    <td><%= link_to 'Edit', edit_winner_path(winner) %></td>
    <td><%= link_to 'Destroy', winner, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Winner', new_winner_path %>

app/views/winners/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_winner_path(@winner) %> |
<%= link_to 'Back', winners_path %>